### ISSUE TITLE
License of language.svg

### ISSUE THREAD

**Issue by rafaelgieschke** [mdn/mdn-dinocons#18]
`general/language.svg` was introduced in <https://github.com/mdn/mdn-dinocons/pull/17>.

Due to its non-free license (see, e.g., <https://github.com/creativecommons/creativecommons.org/issues/1194>), I think you cannot legally distribute it under MPL 2.0, though.

**Comment by schalkneethling** [comment]
> `general/language.svg` was introduced in #17.
> 
> Due to its non-free license (see, e.g., [creativecommons/creativecommons.org#1194](https://github.com/creativecommons/creativecommons.org/issues/1194)), I think you cannot legally distribute it under MPL 2.0, though.

Thank you for bringing our attention to this. We will soon be replacing this with an alternate icon. I will keep this issue open until we have done so.
